/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { DoubleSide, sRGBEncoding, Color } from 'three';
import { useGLTF, useTexture, OrbitControls } from '@react-three/drei';
import bakedWeb from './baked_web.jpg';
import canMatcap from './can_matcap2.png';
import textMatcap from './text_matcap.png';
import { useThree, useFrame } from '@react-three/fiber';

export default function BdHero(props) {
  const group = useRef();
  const controls = useRef();
  const { nodes } = useGLTF('/bd_hero.glb');

  const bakedWebTexture = useTexture(bakedWeb);
  bakedWebTexture.flipY = false;
  bakedWebTexture.encoding = sRGBEncoding;
  const canMatcapTexture = useTexture(canMatcap);
  canMatcapTexture.encoding = sRGBEncoding;
  const textMatcapTexture = useTexture(textMatcap);

  const myCamera = useThree((state) => state.camera);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.left_wall.geometry}
        position={[-3.39, 6.34, 1.81]}
        rotation={[0, -1.57, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.right_wall.geometry}
        position={[3.07, 6.31, -3.87]}
        rotation={[0, -1.57, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.wall_shelf.geometry}
        position={[-2.48, 4.11, 0.45]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Circle.geometry}
        position={[-2.8, 3.77, 1.11]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Circle001.geometry}
        position={[-2.8, 3.77, -0.59]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube018.geometry}
        position={[-2.69, 4.94, 1.17]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube019.geometry}
        position={[-2.7, 4.75, 1.02]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube020.geometry}
        position={[-2.39, 4.64, 1.17]}
        rotation={[0, -1.57, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube021.geometry}
        position={[-2.7, 4.75, 1.27]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube022.geometry}
        position={[-2.62, 5.15, 0.84]}
        rotation={[-Math.PI, -0.11, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube023.geometry}
        position={[-2.65, 4.91, 0.72]}
        rotation={[-Math.PI, -0.11, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube024.geometry}
        position={[-2.32, 4.77, 0.82]}
        rotation={[0, -1.46, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube025.geometry}
        position={[-2.62, 4.91, 0.92]}
        rotation={[-Math.PI, -0.11, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube026.geometry}
        position={[-2.63, 4.3, 0.11]}
        rotation={[-1.57, 0, 2.88]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube027.geometry}
        position={[-2.61, 4.42, 0.11]}
        rotation={[-1.57, 0, 2.88]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube028.geometry}
        position={[-2.32, 4.32, 0.19]}
        rotation={[3.13, -1.31, 1.56]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube029.geometry}
        position={[-2.61, 4.18, 0.11]}
        rotation={[-1.57, 0, 2.88]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube030.geometry}
        position={[-2.69, 4.94, -0.44]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube031.geometry}
        position={[-2.7, 4.95, -0.53]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube032.geometry}
        position={[-2.39, 4.65, -0.44]}
        rotation={[0, -1.57, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube033.geometry}
        position={[-2.7, 4.75, -0.38]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube034.geometry}
        position={[-2.56, 4.94, -0.67]}
        rotation={[-Math.PI, -0.07, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube035.geometry}
        position={[-2.57, 4.75, -0.76]}
        rotation={[-Math.PI, -0.07, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube036.geometry}
        position={[-2.26, 4.65, -0.68]}
        rotation={[0, -1.5, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube037.geometry}
        position={[-2.56, 4.75, -0.6]}
        rotation={[-Math.PI, -0.07, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array.geometry}
        position={[-2.41, 0.83, 2.03]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.foundation.geometry}
        position={[3.07, -0.55, 1.48]}
        rotation={[0, -1.57, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.rug.geometry}
        position={[1.76, 0.95, 0.34]}
        rotation={[-Math.PI, 0, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array001.geometry}
        position={[-1.71, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array002.geometry}
        position={[-0.83, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array003.geometry}
        position={[0.04, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array004.geometry}
        position={[0.92, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array005.geometry}
        position={[1.79, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array006.geometry}
        position={[2.67, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array007.geometry}
        position={[3.54, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array008.geometry}
        position={[4.42, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array009.geometry}
        position={[5.29, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Floor_Array010.geometry}
        position={[6.17, 0.8, 1.5]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube.geometry}
        position={[4.73, 2.73, -2.64]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube001.geometry}
        position={[4.73, 1.73, -2.64]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder006.geometry}
        position={[6.19, 2.05, -2.39]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder007.geometry}
        position={[6.19, 2.05, -3.07]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder008.geometry}
        position={[3.25, 2.05, -2.39]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder009.geometry}
        position={[3.25, 2.05, -3.07]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.base.geometry}
        position={[5.41, 2.78, -2.79]}
        scale={[0.46, 0.18, 0.46]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.page.geometry}
        position={[3.85, 2.8, -2.63]}
        rotation={[0, 0.12, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.page001.geometry}
        position={[4, 2.82, -2.75]}
        rotation={[0, 0.23, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.page002.geometry}
        position={[4.25, 2.8, -2.65]}
        rotation={[0, 0.01, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube039.geometry}
        position={[4.75, 1.97, -2.62]}
        rotation={[0, 0.16, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube040.geometry}
        position={[4.75, 2.21, -2.64]}
        rotation={[0, 0.16, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube041.geometry}
        position={[4.8, 2.16, -2.34]}
        rotation={[0, 0.16, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cylinder010.geometry} position={[-0.74, 1.66, 0.2]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cylinder011.geometry} position={[-0.74, 2.13, 0.2]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder012.geometry}
        position={[-0.74, 1.32, -0.09]}
        rotation={[1.4, 0, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Elbow_Joint013.geometry}
        position={[-0.74, 1.26, -0.34]}
        rotation={[0, Math.PI / 2, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder013.geometry}
        position={[-0.74, 1.05, -0.31]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder014.geometry}
        position={[-0.74, 1.05, -0.42]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder015.geometry}
        position={[-0.99, 1.32, 0.34]}
        rotation={[1.66, 0.15, -2.1]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Elbow_Joint003.geometry}
        position={[-1.21, 1.26, 0.46]}
        rotation={[-Math.PI, -Math.PI / 6, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder016.geometry}
        position={[-1.18, 1.05, 0.45]}
        rotation={[Math.PI / 2, 0, -2.09]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder017.geometry}
        position={[-1.27, 1.05, 0.5]}
        rotation={[Math.PI / 2, 0, -2.09]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder018.geometry}
        position={[-0.49, 1.32, 0.34]}
        rotation={[1.66, -0.15, 2.1]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Elbow_Joint004.geometry}
        position={[-0.28, 1.26, 0.47]}
        rotation={[0, -Math.PI / 6, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder019.geometry}
        position={[-0.3, 1.05, 0.45]}
        rotation={[Math.PI / 2, 0, 2.09]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder020.geometry}
        position={[-0.21, 1.05, 0.5]}
        rotation={[Math.PI / 2, 0, 2.09]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.B.geometry}
        position={[0.71, 5.84, -3.43]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[41.15, 49.94, 41.15]}
      >
        <meshMatcapMaterial matcap={canMatcapTexture} color={0x34252f} />
      </mesh>
      <mesh
        geometry={nodes.D.geometry}
        position={[2.06, 4.8, -3.43]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[41.15, 49.94, 41.15]}
      >
        <meshMatcapMaterial matcap={canMatcapTexture} color={0xb2a2ad} />
      </mesh>
      <mesh
        geometry={nodes.leg_1.geometry}
        position={[-2.39, 1.71, -1.29]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.leg_2.geometry}
        position={[-1.18, 1.71, -1.3]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.leg_3.geometry}
        position={[-1.17, 1.71, 1.9]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.leg_4.geometry}
        position={[-2.38, 1.71, 1.92]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Tabletop.geometry}
        position={[-1.58, 2.55, 0.36]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.chassis.geometry}
        position={[-1.67, 2.64, 1.14]}
        rotation={[0, 0, -0.02]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.keys.geometry}
        position={[-1.69, 2.66, 0.99]}
        rotation={[0, 0, -0.02]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.trackpad.geometry}
        position={[-1.27, 2.65, 1.08]}
        rotation={[0, 0, -0.02]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.touchbar.geometry}
        position={[-1.93, 2.66, 1.11]}
        rotation={[0, 0, -0.02]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.chassis_top.geometry}
        position={[-2.18, 3.17, 1.11]}
        rotation={[0, 0, -1.25]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.screen.geometry}
        position={[-2.17, 3.19, 0.99]}
        rotation={[0, 0, -1.25]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.laptop_b.geometry}
        position={[-2.03, 2.78, 1.24]}
        rotation={[Math.PI / 2, 0.33, -Math.PI / 2]}
        scale={[5.99, 5.99, 5.99]}
      >
        <meshBasicMaterial color={0x34252f} />
      </mesh>
      <mesh
        geometry={nodes.laptop_d.geometry}
        position={[-2.03, 2.78, 1.24]}
        rotation={[Math.PI / 2, 0.33, -Math.PI / 2]}
        scale={[5.99, 5.99, 5.99]}
      >
        <meshBasicMaterial color={0x80747c} />
      </mesh>
      <mesh
        geometry={nodes.Cylinder005.geometry}
        position={[-2.11, 2.79, -0.14]}
        rotation={[0, -1.07, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.Cube038.geometry}
        position={[-2.05, 2.63, -0.11]}
        rotation={[0, 0.36, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.handle.geometry}
        position={[-1.88, 2.8, -0.26]}
        rotation={[0, -1.07, -Math.PI / 2]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.chassis_top001.geometry}
        position={[-1.52, 2.64, -0.82]}
        rotation={[Math.PI, -1.13, Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.screen001.geometry}
        position={[-1.53, 2.64, -0.82]}
        rotation={[0, 1.13, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.ipad_b.geometry}
        position={[-1.4, 2.64, -0.52]}
        rotation={[0, 1.13, 0]}
        scale={[5.31, 5.31, 5.31]}
      >
        <meshBasicMaterial color={0x34252f} />
      </mesh>
      <mesh
        geometry={nodes.ipad_d.geometry}
        position={[-1.4, 2.64, -0.52]}
        rotation={[0, 1.13, 0]}
        scale={[5.31, 5.31, 5.31]}
      >
        <meshBasicMaterial color={0x80747c} />
      </mesh>
      <mesh geometry={nodes.Cube002.geometry} position={[-2.22, 3.6, -2.21]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cube003.geometry} position={[-1.36, 3.29, -2.2]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cube004.geometry} position={[-2.22, 3.6, -3.05]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cube005.geometry} position={[-1.36, 3.29, -3.06]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.lamp_1_emissive.geometry}
        position={[-1.79, 4.48, -2.63]}
      >
        <meshBasicMaterial color={0xffe3ba} side={DoubleSide} />
      </mesh>
      <mesh geometry={nodes.Cube007.geometry} position={[-1.66, 2.99, -2.5]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cube016.geometry} position={[-1.67, 2, -2.51]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.lamp_1_emissive001.geometry}
        position={[-1.79, 4.95, -2.63]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cube009.geometry} position={[-2.22, 2.94, 3.71]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cube010.geometry} position={[-1.36, 2.94, 3.71]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cube011.geometry} position={[-2.21, 2.94, 2.86]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cube012.geometry} position={[-1.36, 2.94, 2.85]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.lamp_2_emissive.geometry}
        position={[-1.79, 4.48, 3.28]}
      >
        <meshBasicMaterial color={0xffe3ba} side={DoubleSide} />
      </mesh>
      <mesh geometry={nodes.Cube014.geometry} position={[-1.71, 2.99, 3.29]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Cube015.geometry} position={[-1.71, 2, 3.29]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.lamp_1_emissive002.geometry}
        position={[-1.79, 4.95, 3.28]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.camera.geometry}
        position={[-1.72, 3.2, 3.28]}
        rotation={[0, -0.13, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.lens_shaft.geometry}
        position={[-1.59, 3.17, 3.29]}
        rotation={[0, -0.13, -Math.PI / 2]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.lens.geometry}
        position={[-1.52, 3.17, 3.3]}
        rotation={[0, -0.13, -Math.PI / 2]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.lens_shaft001.geometry}
        position={[-1.72, 3.34, 3.12]}
        rotation={[0, -0.13, -Math.PI]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.camera001.geometry}
        position={[-1.75, 3.34, 3.42]}
        rotation={[0, -0.13, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh
        geometry={nodes.camera002.geometry}
        position={[-1.61, 3.28, 3.14]}
        rotation={[0, -0.13, 0]}
      >
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <mesh geometry={nodes.Can.geometry} position={[2.05, 1.28, -2.78]}>
        <meshMatcapMaterial matcap={canMatcapTexture} />
      </mesh>
      <mesh geometry={nodes.Soil.geometry} position={[2.05, 1.5, -2.78]}>
        <meshBasicMaterial map={bakedWebTexture} />
      </mesh>
      <OrbitControls camera={myCamera} ref={controls} />
    </group>
  );
}

useGLTF.preload('/bd_hero.glb');
