/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes } = useGLTF('/beresford_design.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.mac_pro_emissive.geometry}
        material={nodes.mac_pro_emissive.material}
        position={[0.86955, 0.30488, -0.54437]}
      />
      <mesh
        geometry={nodes.phone_emissive.geometry}
        material={nodes.phone_emissive.material}
        position={[0.01893, 0.78195, -0.80597]}
      />
      <mesh
        geometry={nodes.monitor_emissive.geometry}
        material={nodes.monitor_emissive.material}
        position={[0.34019, 1.12988, -0.91913]}
      />
      <mesh
        geometry={nodes.ipad_emissive001.geometry}
        material={nodes.ipad_emissive001.material}
        position={[-1.33327, 1.38233, -0.77324]}
      />
      <mesh
        geometry={nodes.ipad_emissive002.geometry}
        material={nodes.ipad_emissive002.material}
        position={[-0.90973, 0.98622, -0.77324]}
      />
      <mesh
        geometry={nodes.ipad_emissive.geometry}
        material={nodes.ipad_emissive.material}
        position={[-1.33327, 0.6179, -0.77324]}
      />
      <mesh
        geometry={nodes.email_emissive.geometry}
        material={nodes.email_emissive.material}
        position={[-1.54201, 1.74999, -0.82321]}
      />
      <mesh
        geometry={nodes.insta_emissive.geometry}
        material={nodes.insta_emissive.material}
        position={[-1.2595, 1.74999, -0.82434]}
      />
      <mesh
        geometry={nodes.linkedin_emissive.geometry}
        material={nodes.linkedin_emissive.material}
        position={[-0.9821, 1.74999, -0.82434]}
      />
      <mesh
        geometry={nodes.table_emissive.geometry}
        material={nodes.table_emissive.material}
        position={[1.19391, 0.46596, -0.72178]}
      />
      <mesh
        geometry={nodes.shelving_emissive.geometry}
        material={nodes.shelving_emissive.material}
        position={[-1.1789, 0.51015, -0.87188]}
      />
      <mesh
        geometry={nodes.lamp_emissive_orange.geometry}
        material={nodes.lamp_emissive_orange.material}
        position={[1.62294, 1.49388, -0.73567]}
      />
      <mesh
        geometry={nodes.lamp_emissive_purple.geometry}
        material={nodes.lamp_emissive_purple.material}
        position={[1.62294, 1.49388, -0.73567]}
      />
      <mesh
        geometry={nodes.lamp_emissive_pink.geometry}
        material={nodes.lamp_emissive_pink.material}
        position={[1.62294, 1.49388, -0.73567]}
      />
      <mesh
        geometry={nodes.github_emissive.geometry}
        material={nodes.github_emissive.material}
        position={[-0.70014, 1.74999, -0.82434]}
      />
      <mesh
        geometry={nodes.bake2.geometry}
        material={nodes.bake2.material}
        position={[0.99771, 0.87454, -1.053]}
      />
      <mesh
        geometry={nodes.leaf.geometry}
        material={nodes.leaf.material}
        position={[-0.23566, 1.099, -0.96267]}
      />
      <mesh
        geometry={nodes.leaf001.geometry}
        material={nodes.leaf001.material}
        position={[-0.24847, 0.94632, -0.97138]}
      />
      <mesh
        geometry={nodes.leaf002.geometry}
        material={nodes.leaf002.material}
        position={[-0.23635, 1.07228, -0.97535]}
      />
      <mesh
        geometry={nodes.leaf003.geometry}
        material={nodes.leaf003.material}
        position={[-0.22061, 0.99009, -0.95713]}
      />
      <mesh
        geometry={nodes.leaf004.geometry}
        material={nodes.leaf004.material}
        position={[-0.19121, 0.95672, -0.96975]}
      />
      <mesh
        geometry={nodes.leaf005.geometry}
        material={nodes.leaf005.material}
        position={[-0.18227, 1.05066, -0.99789]}
      />
      <mesh
        geometry={nodes.leaf006.geometry}
        material={nodes.leaf006.material}
        position={[-0.25628, 1.03472, -0.98371]}
      />
      <mesh
        geometry={nodes.leaf007.geometry}
        material={nodes.leaf007.material}
        position={[-0.26338, 0.98175, -0.99677]}
      />
      <mesh
        geometry={nodes.leaf008.geometry}
        material={nodes.leaf008.material}
        position={[-0.24424, 0.9702, -0.94746]}
      />
      <mesh
        geometry={nodes.leaf009.geometry}
        material={nodes.leaf009.material}
        position={[-0.19134, 1.01348, -0.966]}
      />
      <mesh
        geometry={nodes.leaf010.geometry}
        material={nodes.leaf010.material}
        position={[-0.17853, 1.08602, -0.98267]}
      />
      <mesh
        geometry={nodes.bake3.geometry}
        material={nodes.bake3.material}
        position={[0.86468, 0.35838, -0.66076]}
      />
      <mesh
        geometry={nodes.bake4.geometry}
        material={nodes.bake4.material}
        position={[0.01111, 1.01411, -1.13694]}
      />
      <mesh
        geometry={nodes.bake5.geometry}
        material={nodes.bake5.material}
        position={[-0.79024, -0.91263, -0.7532]}
      />
      <mesh
        geometry={nodes.bake6.geometry}
        material={nodes.bake6.material}
        position={[0.48428, 1.41479, 2.21467]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.bake7.geometry}
        material={nodes.bake7.material}
        position={[0.48428, 1.41479, 2.21467]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.bake8.geometry}
        material={nodes.bake8.material}
        position={[0.48428, 1.41479, 2.21467]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/beresford_design.glb');
