/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/hero_model.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.letters.geometry}
        material={nodes.letters.material}
        position={[0.05574, 6.93339, -0.00698]}
      />
      <mesh
        geometry={nodes.air_rock001.geometry}
        material={nodes.air_rock001.material}
        position={[-3.14247, 1.59546, 3.03652]}
      />
      <mesh
        geometry={nodes.air_rock002.geometry}
        material={nodes.air_rock002.material}
        position={[-2.40939, 11.24023, -2.64953]}
      />
      <mesh
        geometry={nodes.air_rock003.geometry}
        material={nodes.air_rock003.material}
        position={[3.94263, 7.24577, -2.62799]}
      />
      <mesh
        geometry={nodes.air_rock.geometry}
        material={nodes.air_rock.material}
        position={[3.15335, 3.2013, 2.33815]}
      />
      <mesh
        geometry={nodes.platform.geometry}
        material={nodes.platform.material}
        position={[-0.03233, -1.16806, -1.12225]}
      />
      <mesh
        geometry={nodes.emissive.geometry}
        material={nodes.emissive.material}
        position={[-0.20013, -0.70351, 0.21569]}
      />
    </group>
  )
}

useGLTF.preload('/hero_model.glb')
